FROM registry.access.redhat.com/rhel7/support-tools

RUN subscription-manager repos --enable=rhel-7-server-extras-rpms

RUN INSTALL_PKGS="podman" && \
    microdnf -y install $INSTALL_PKGS && \
    rpm -V --nosize --nofiledigest --nomtime $INSTALL_PKGS && \
    microdnf clean all && \
    rm -rf /usr/local/man


CMD ["/usr/bin/bash"]